// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: test_suites/networkconfig/config_expectations/config_expectations.proto

package config_expectations_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConfigExpectations struct {
	state                         protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ConfigExpectations *[]*SystemConfig       `protobuf:"bytes,1,rep,name=config_expectations,json=configExpectations"`
	unknownFields                 protoimpl.UnknownFields
	sizeCache                     protoimpl.SizeCache
}

func (x *ConfigExpectations) Reset() {
	*x = ConfigExpectations{}
	mi := &file_test_suites_networkconfig_config_expectations_config_expectations_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigExpectations) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigExpectations) ProtoMessage() {}

func (x *ConfigExpectations) ProtoReflect() protoreflect.Message {
	mi := &file_test_suites_networkconfig_config_expectations_config_expectations_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ConfigExpectations) GetConfigExpectations() []*SystemConfig {
	if x != nil {
		if x.xxx_hidden_ConfigExpectations != nil {
			return *x.xxx_hidden_ConfigExpectations
		}
	}
	return nil
}

func (x *ConfigExpectations) SetConfigExpectations(v []*SystemConfig) {
	x.xxx_hidden_ConfigExpectations = &v
}

type ConfigExpectations_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	ConfigExpectations []*SystemConfig
}

func (b0 ConfigExpectations_builder) Build() *ConfigExpectations {
	m0 := &ConfigExpectations{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_ConfigExpectations = &b.ConfigExpectations
	return m0
}

// Configuration for a particular variant of a machine.
// Keyed on machine type and NIC types.
type SystemConfig struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Description *string                `protobuf:"bytes,1,opt,name=description"`
	xxx_hidden_MachineType *string                `protobuf:"bytes,2,opt,name=machine_type,json=machineType"`
	xxx_hidden_Nics        *[]*NicExpectation     `protobuf:"bytes,4,rep,name=nics"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *SystemConfig) Reset() {
	*x = SystemConfig{}
	mi := &file_test_suites_networkconfig_config_expectations_config_expectations_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemConfig) ProtoMessage() {}

func (x *SystemConfig) ProtoReflect() protoreflect.Message {
	mi := &file_test_suites_networkconfig_config_expectations_config_expectations_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SystemConfig) GetDescription() string {
	if x != nil {
		if x.xxx_hidden_Description != nil {
			return *x.xxx_hidden_Description
		}
		return ""
	}
	return ""
}

func (x *SystemConfig) GetMachineType() string {
	if x != nil {
		if x.xxx_hidden_MachineType != nil {
			return *x.xxx_hidden_MachineType
		}
		return ""
	}
	return ""
}

func (x *SystemConfig) GetNics() []*NicExpectation {
	if x != nil {
		if x.xxx_hidden_Nics != nil {
			return *x.xxx_hidden_Nics
		}
	}
	return nil
}

func (x *SystemConfig) SetDescription(v string) {
	x.xxx_hidden_Description = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *SystemConfig) SetMachineType(v string) {
	x.xxx_hidden_MachineType = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *SystemConfig) SetNics(v []*NicExpectation) {
	x.xxx_hidden_Nics = &v
}

func (x *SystemConfig) HasDescription() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *SystemConfig) HasMachineType() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *SystemConfig) ClearDescription() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Description = nil
}

func (x *SystemConfig) ClearMachineType() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_MachineType = nil
}

type SystemConfig_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// An informational description summarizing the configuration.
	// Should only be used for logging/documentation purposes.
	Description *string
	// The GCE machine type e.g. "n2d-standard-2".
	MachineType *string
	// NICs in the VM. This includes any device expected to be created by the
	// GCE stack, but not any created by the user (e.g. not `lo` or `docker0`).
	Nics []*NicExpectation
}

func (b0 SystemConfig_builder) Build() *SystemConfig {
	m0 := &SystemConfig{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Description != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_Description = b.Description
	}
	if b.MachineType != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_MachineType = b.MachineType
	}
	x.xxx_hidden_Nics = &b.Nics
	return m0
}

type NicExpectation struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Type        *string                `protobuf:"bytes,1,opt,name=type"`
	xxx_hidden_TxQueues    *[]*TxQueue            `protobuf:"bytes,2,rep,name=tx_queues,json=txQueues"`
	xxx_hidden_RxQueues    *[]*RxQueue            `protobuf:"bytes,3,rep,name=rx_queues,json=rxQueues"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *NicExpectation) Reset() {
	*x = NicExpectation{}
	mi := &file_test_suites_networkconfig_config_expectations_config_expectations_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NicExpectation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NicExpectation) ProtoMessage() {}

func (x *NicExpectation) ProtoReflect() protoreflect.Message {
	mi := &file_test_suites_networkconfig_config_expectations_config_expectations_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *NicExpectation) GetType() string {
	if x != nil {
		if x.xxx_hidden_Type != nil {
			return *x.xxx_hidden_Type
		}
		return ""
	}
	return ""
}

func (x *NicExpectation) GetTxQueues() []*TxQueue {
	if x != nil {
		if x.xxx_hidden_TxQueues != nil {
			return *x.xxx_hidden_TxQueues
		}
	}
	return nil
}

func (x *NicExpectation) GetRxQueues() []*RxQueue {
	if x != nil {
		if x.xxx_hidden_RxQueues != nil {
			return *x.xxx_hidden_RxQueues
		}
	}
	return nil
}

func (x *NicExpectation) SetType(v string) {
	x.xxx_hidden_Type = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *NicExpectation) SetTxQueues(v []*TxQueue) {
	x.xxx_hidden_TxQueues = &v
}

func (x *NicExpectation) SetRxQueues(v []*RxQueue) {
	x.xxx_hidden_RxQueues = &v
}

func (x *NicExpectation) HasType() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *NicExpectation) ClearType() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Type = nil
}

type NicExpectation_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The type of NIC, corresponding to the type used in the GCE API, e.g.
	// "VIRTIO_NET", "GVNIC", "IDPF".
	Type *string
	// Transmit queues for this NIC.
	TxQueues []*TxQueue
	// Receive queues for this NIC.
	RxQueues []*RxQueue
}

func (b0 NicExpectation_builder) Build() *NicExpectation {
	m0 := &NicExpectation{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Type != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_Type = b.Type
	}
	x.xxx_hidden_TxQueues = &b.TxQueues
	x.xxx_hidden_RxQueues = &b.RxQueues
	return m0
}

type RxQueue struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Index       int32                  `protobuf:"varint,1,opt,name=index"`
	xxx_hidden_IrqCpulist  *string                `protobuf:"bytes,2,opt,name=irq_cpulist,json=irqCpulist"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *RxQueue) Reset() {
	*x = RxQueue{}
	mi := &file_test_suites_networkconfig_config_expectations_config_expectations_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RxQueue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RxQueue) ProtoMessage() {}

func (x *RxQueue) ProtoReflect() protoreflect.Message {
	mi := &file_test_suites_networkconfig_config_expectations_config_expectations_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RxQueue) GetIndex() int32 {
	if x != nil {
		return x.xxx_hidden_Index
	}
	return 0
}

func (x *RxQueue) GetIrqCpulist() string {
	if x != nil {
		if x.xxx_hidden_IrqCpulist != nil {
			return *x.xxx_hidden_IrqCpulist
		}
		return ""
	}
	return ""
}

func (x *RxQueue) SetIndex(v int32) {
	x.xxx_hidden_Index = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *RxQueue) SetIrqCpulist(v string) {
	x.xxx_hidden_IrqCpulist = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *RxQueue) HasIndex() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *RxQueue) HasIrqCpulist() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *RxQueue) ClearIndex() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Index = 0
}

func (x *RxQueue) ClearIrqCpulist() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_IrqCpulist = nil
}

type RxQueue_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The OS's index for the queue. For instance, the rx queue at index 0
	// will tend to manifest in the OS as `rx-0`.
	Index *int32
	// The cpuset "List Format" representation of the IRQ affinity of this queue.
	IrqCpulist *string
}

func (b0 RxQueue_builder) Build() *RxQueue {
	m0 := &RxQueue{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Index != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Index = *b.Index
	}
	if b.IrqCpulist != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_IrqCpulist = b.IrqCpulist
	}
	return m0
}

type TxQueue struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Index       int32                  `protobuf:"varint,1,opt,name=index"`
	xxx_hidden_IrqCpulist  *string                `protobuf:"bytes,2,opt,name=irq_cpulist,json=irqCpulist"`
	xxx_hidden_XpsCpulist  *string                `protobuf:"bytes,3,opt,name=xps_cpulist,json=xpsCpulist"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *TxQueue) Reset() {
	*x = TxQueue{}
	mi := &file_test_suites_networkconfig_config_expectations_config_expectations_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxQueue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxQueue) ProtoMessage() {}

func (x *TxQueue) ProtoReflect() protoreflect.Message {
	mi := &file_test_suites_networkconfig_config_expectations_config_expectations_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *TxQueue) GetIndex() int32 {
	if x != nil {
		return x.xxx_hidden_Index
	}
	return 0
}

func (x *TxQueue) GetIrqCpulist() string {
	if x != nil {
		if x.xxx_hidden_IrqCpulist != nil {
			return *x.xxx_hidden_IrqCpulist
		}
		return ""
	}
	return ""
}

func (x *TxQueue) GetXpsCpulist() string {
	if x != nil {
		if x.xxx_hidden_XpsCpulist != nil {
			return *x.xxx_hidden_XpsCpulist
		}
		return ""
	}
	return ""
}

func (x *TxQueue) SetIndex(v int32) {
	x.xxx_hidden_Index = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *TxQueue) SetIrqCpulist(v string) {
	x.xxx_hidden_IrqCpulist = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *TxQueue) SetXpsCpulist(v string) {
	x.xxx_hidden_XpsCpulist = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *TxQueue) HasIndex() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *TxQueue) HasIrqCpulist() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *TxQueue) HasXpsCpulist() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *TxQueue) ClearIndex() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Index = 0
}

func (x *TxQueue) ClearIrqCpulist() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_IrqCpulist = nil
}

func (x *TxQueue) ClearXpsCpulist() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_XpsCpulist = nil
}

type TxQueue_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The OS's index for the queue. For instance, the tx queue at index 0
	// will tend to manifest in the OS as `tx-0`.
	Index *int32
	// The cpuset "List Format" representation of the IRQ affinity of this queue.
	IrqCpulist *string
	// The cpuset "List Format" representation of the CPUS configured for XPS
	// for this queue.
	XpsCpulist *string
}

func (b0 TxQueue_builder) Build() *TxQueue {
	m0 := &TxQueue{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Index != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_Index = *b.Index
	}
	if b.IrqCpulist != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_IrqCpulist = b.IrqCpulist
	}
	if b.XpsCpulist != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_XpsCpulist = b.XpsCpulist
	}
	return m0
}

var File_test_suites_networkconfig_config_expectations_config_expectations_proto protoreflect.FileDescriptor

const file_test_suites_networkconfig_config_expectations_config_expectations_proto_rawDesc = "" +
	"\n" +
	"Gtest_suites/networkconfig/config_expectations/config_expectations.proto\x12Jgithub_com.googlecloudplatform.cloud_image_tests.test_suites.networkconfig\"\xa0\x01\n" +
	"\x12ConfigExpectations\x12\x89\x01\n" +
	"\x13config_expectations\x18\x01 \x03(\v2X.github_com.googlecloudplatform.cloud_image_tests.test_suites.networkconfig.SystemConfigR\x12configExpectations\"\xc3\x01\n" +
	"\fSystemConfig\x12 \n" +
	"\vdescription\x18\x01 \x01(\tR\vdescription\x12!\n" +
	"\fmachine_type\x18\x02 \x01(\tR\vmachineType\x12n\n" +
	"\x04nics\x18\x04 \x03(\v2Z.github_com.googlecloudplatform.cloud_image_tests.test_suites.networkconfig.NicExpectationR\x04nics\"\x88\x02\n" +
	"\x0eNicExpectation\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12p\n" +
	"\ttx_queues\x18\x02 \x03(\v2S.github_com.googlecloudplatform.cloud_image_tests.test_suites.networkconfig.TxQueueR\btxQueues\x12p\n" +
	"\trx_queues\x18\x03 \x03(\v2S.github_com.googlecloudplatform.cloud_image_tests.test_suites.networkconfig.RxQueueR\brxQueues\"@\n" +
	"\aRxQueue\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\x12\x1f\n" +
	"\virq_cpulist\x18\x02 \x01(\tR\n" +
	"irqCpulist\"a\n" +
	"\aTxQueue\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\x12\x1f\n" +
	"\virq_cpulist\x18\x02 \x01(\tR\n" +
	"irqCpulist\x12\x1f\n" +
	"\vxps_cpulist\x18\x03 \x01(\tR\n" +
	"xpsCpulistB7Z5./test_suites/networkconfig/config_expectations_protob\beditionsp\xe9\a"

var file_test_suites_networkconfig_config_expectations_config_expectations_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_test_suites_networkconfig_config_expectations_config_expectations_proto_goTypes = []any{
	(*ConfigExpectations)(nil), // 0: github_com.googlecloudplatform.cloud_image_tests.test_suites.networkconfig.ConfigExpectations
	(*SystemConfig)(nil),       // 1: github_com.googlecloudplatform.cloud_image_tests.test_suites.networkconfig.SystemConfig
	(*NicExpectation)(nil),     // 2: github_com.googlecloudplatform.cloud_image_tests.test_suites.networkconfig.NicExpectation
	(*RxQueue)(nil),            // 3: github_com.googlecloudplatform.cloud_image_tests.test_suites.networkconfig.RxQueue
	(*TxQueue)(nil),            // 4: github_com.googlecloudplatform.cloud_image_tests.test_suites.networkconfig.TxQueue
}
var file_test_suites_networkconfig_config_expectations_config_expectations_proto_depIdxs = []int32{
	1, // 0: github_com.googlecloudplatform.cloud_image_tests.test_suites.networkconfig.ConfigExpectations.config_expectations:type_name -> github_com.googlecloudplatform.cloud_image_tests.test_suites.networkconfig.SystemConfig
	2, // 1: github_com.googlecloudplatform.cloud_image_tests.test_suites.networkconfig.SystemConfig.nics:type_name -> github_com.googlecloudplatform.cloud_image_tests.test_suites.networkconfig.NicExpectation
	4, // 2: github_com.googlecloudplatform.cloud_image_tests.test_suites.networkconfig.NicExpectation.tx_queues:type_name -> github_com.googlecloudplatform.cloud_image_tests.test_suites.networkconfig.TxQueue
	3, // 3: github_com.googlecloudplatform.cloud_image_tests.test_suites.networkconfig.NicExpectation.rx_queues:type_name -> github_com.googlecloudplatform.cloud_image_tests.test_suites.networkconfig.RxQueue
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_test_suites_networkconfig_config_expectations_config_expectations_proto_init() }
func file_test_suites_networkconfig_config_expectations_config_expectations_proto_init() {
	if File_test_suites_networkconfig_config_expectations_config_expectations_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_test_suites_networkconfig_config_expectations_config_expectations_proto_rawDesc), len(file_test_suites_networkconfig_config_expectations_config_expectations_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_test_suites_networkconfig_config_expectations_config_expectations_proto_goTypes,
		DependencyIndexes: file_test_suites_networkconfig_config_expectations_config_expectations_proto_depIdxs,
		MessageInfos:      file_test_suites_networkconfig_config_expectations_config_expectations_proto_msgTypes,
	}.Build()
	File_test_suites_networkconfig_config_expectations_config_expectations_proto = out.File
	file_test_suites_networkconfig_config_expectations_config_expectations_proto_goTypes = nil
	file_test_suites_networkconfig_config_expectations_config_expectations_proto_depIdxs = nil
}
